apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: tvrnxr/px-client-side-prod:v5
          command: ["npm", "run", "preview"]
          ports:
            - containerPort: 8000
