import MOJO from "../assets/products/MOJO.jpg";
export const productList = [
  {
    name: "JOKER",
    category: "poster",
    id: "1vd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "DOMO",
    category: "poster",
    id: "10d",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "pop-art",
  },
  {
    name: "SPICY",
    category: "poster",
    id: "12F",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "NERD",
    category: "Sticker",
    id: "1od",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "musique",
  },
  {
    name: "teuf",
    category: "Sticker",
    id: "1olps",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "art",
  },
  {
    name: "mach",
    category: "poster",
    id: "1sokd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "BLOCKBUSTER",
    category: "poster",
    id: "1sbod",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "AVATARD",
    category: "poster",
    id: "1sodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "bande-déssinée",
  },
  {
    name: "moshino",
    category: "sticker",
    id: "1sfodn",
    available: true,
    prix: "3.00 XOF",
    cover: MOJO,
    genre: "mode",
  },
  {
    name: "big mom",
    category: "poster",
    id: "1sfodvn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },
  {
    name: "Ace",
    category: "poster",
    id: "1sffodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },
  {
    name: "asap rocky",
    category: "poster",
    id: "1sffodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "musique",
  },
  {
    name: "astroworld",
    category: "sticker",
    id: "1sffohdn",
    available: true,
    prix: "3.00 XOF",
    cover: MOJO,
    genre: "pop-art",
  },
  {
    name: "DONALD",
    category: "poster",
    id: "1sffodhn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "bande-déssinée",
  },
  {
    name: "DORA",
    category: "poster",
    id: "1sffCodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },

  {
    name: "JOKER",
    category: "poster",
    id: "1vkd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "DOMO",
    category: "poster",
    id: "10gd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "pop-art",
  },
  {
    name: "SPICY",
    category: "poster",
    id: "12jdF",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "NERD",
    category: "Sticker",
    id: "1qaod",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "musique",
  },
  {
    name: "teuf",
    category: "Sticker",
    id: "1olrtps",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "art",
  },
  {
    name: "mach",
    category: "poster",
    id: "1soytkd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "BLOCKBUSTER",
    category: "poster",
    id: "1sbcxod",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "AVATARD",
    category: "poster",
    id: "1sosddn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "bande-déssinée",
  },
  {
    name: "moshino",
    category: "sticker",
    id: "1sffgodn",
    available: true,
    prix: "3.00 XOF",
    cover: MOJO,
    genre: "mode",
  },
  {
    name: "big mom",
    category: "poster",
    id: "1sfoerdvn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },
  {
    name: "Ace",
    category: "poster",
    id: "1sffzaodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },
  {
    name: "asap rocky",
    category: "poster",
    id: "1sujffodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "musique",
  },
  {
    name: "astroworld",
    category: "sticker",
    id: "1skiffohdn",
    available: true,
    prix: "3.00 XOF",
    cover: MOJO,
    genre: "pop-art",
  },
  {
    name: "DONALD",
    category: "poster",
    id: "1sffodhomn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "bande-déssinée",
  },
  {
    name: "DORA",
    category: "poster",
    id: "1sffCodjnn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "anime",
  },
];
