import MOJO from "../assets/products/MOJO.jpg";
export const productList = [
  {
    name: "JOKER",
    category: "poster",
    id: "1vd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "DOMO",
    category: "poster",
    id: "10d",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "pop-art",
  },
  {
    name: "SPICY",
    category: "poster",
    id: "12F",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "NERD",
    category: "Sticker",
    id: "1od",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "musique",
  },
  {
    name: "teuf",
    category: "Sticker",
    id: "1olps",
    available: true,
    prix: "300 XOF",
    cover: MOJO,
    genre: "art",
  },
  {
    name: "mach",
    category: "poster",
    id: "1sokd",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "BLOCKBUSTER",
    category: "poster",
    id: "1sbod",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "cinéma",
  },
  {
    name: "AVATARD",
    category: "poster",
    id: "1sodn",
    available: true,
    prix: "3.000 XOF",
    cover: MOJO,
    genre: "bande-déssinée",
  },
];
